### ISSUE TITLE
next page is not loaded

### ISSUE THREAD

**Issue by likerainsun** [aesuli/Amazon-downloader#1]
Hello
I have been using this software to crawl amazon reviews.
Recently, I found that it only download the first page of reviews.
I assume Amazon changed the layout of the review pages. 
Do you have any idea where I need to change in the code???

Thank you for sharing this code.

Munhyong Kim

**Comment by aesuli** [comment]
I'm working on fixing it, it should be ready in a few days.

**Comment by likerainsun** [comment]
found it
the last page number is changed to btm not topn

**Comment by likerainsun** [comment]
while($content =~ m#cm_cr_pr_top_link_([0-9]+)#gs ) 
=>
 while($content =~ m#cm_cr_pr_btm_link_([0-9]+)#gs )

Thank you^^

**Comment by aesuli** [comment]
Yes, that fixes one issue. The extract script also stopped working on
".com" reviews due to a layout change on that domain. I'm also working on
that part.
