### ISSUE TITLE
Cannot download reviews from more than 1 page

### ISSUE THREAD

**Issue by arcsoftech** [aesuli/Amazon-downloader#3]
Cannot download reviews from more than 1 page.
Please fix this problem.
I think amazon might have done some changes to its page layout.

**Comment by arcsoftech** [comment]
got the solution
change the following
content =~ m#cm_cr_pr_top_link_([0-9]+)#gs
to
content =~ m#cm_cr_arp_d_paging_btm_([0-9]+)#gs

**Comment by aesuli** [comment]
Good job! I suggest you make a pull request from your repo, to track your contribution.
